times = ('Corinthians', 'Flamengo', 'Atlético-GO', 'Atlético-MG', 'Chape', 'Bahia', 'Botafogo', 'Bragantino','Athletico-PR', 'Ceará', 'Coritiba')
print(f'Os cinco primeiros são {times}')
print('='*50)
print(f'Os cinco primeiros são {times[:5]}')
print('='*50)
print(f'Os três ultimos últimos são {times[-3:]}')
print('='*50)
print(f'Times em ordem Alfabética {sorted(times)}')
print('='*50)
print('A Chape está na {}º posição'.format(times.index('Chape')+1))
